server:
  port: 8503
spring:
  application:
    name: notification-service
  rabbitmq:
    username: serkanp
    password: serkan
  cloud:
    stream:
      bindings:
        input:
          destination: microservicekuyruk
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
    fetchRegistry: true