server:
  port: 8502
spring:
  application:
    name: ticket-service
  rabbitmq:
    username: serkanp
    password: serkan
  cloud:
    stream:
      bindings:
        output:
          destination: microservicekuyruk
  datasource:
    url: jdbc:mysql://localhost:3306/mikroserviceapp
    username: root
    password: serkanpolat
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
    fetchRegistry: true